name: The workflow
on:
  push:
    branches:
      - feature
      - master
  pull_request:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      # initializing
      - name: Initiation message
        run: echo preparing to install

      # Installing
      - name: Installing
        run: npm install
      
      # Testing
      - name: Installing
        run: npm run test

      # Building
      - name: Building
        run: npm run build

      # Confirmation
      - name: Confirming
        run: echo all done!